-- vim.cmd([[
--   highlight IndentBlanklineJess guifg=#2F313C gui=nocombine
-- ]])

-- require('ibl').setup {
--   indent = {
--     char = '│',
--     highlight = {
--       'IndentBlanklineJess',
--     },
--   },
--   exclude = {
--     filetypes = {
--       'help',
--       'terminal',
--       'dashboard',
--       'packer',
--       'lspinfo',
--       'TelescopePrompt',
--       'TelescopeResults',
--     },
--     buftypes = { 'terminal', 'NvimTree' },
--   },
--   scope = {
--     enabled = false,
--   },
--   whitespace = {
--     remove_blankline_trail = true,
--   },
-- }
