vim.o.history=100  -- Reduce history size for better performance
vim.o.ruler=false  -- Modern UIs don't need this
vim.o.showcmd=true
vim.o.incsearch=true
vim.o.laststatus=2
vim.o.showmatch=true
vim.o.wrap=false
vim.o.autoread=true
vim.o.expandtab = true
vim.o.shiftwidth = 2
vim.o.tabstop = 2
vim.o.signcolumn = 'yes:2'
vim.o.relativenumber = true
vim.o.number = true
vim.o.termguicolors = true
vim.o.undofile = true
vim.o.spell = false
vim.o.title = true
vim.o.colorcolumn = '80'
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.wildmode = 'longest:full,full'
vim.o.mouse = 'a'
vim.o.splitright = true
vim.o.splitbelow = true
vim.o.scrolloff = 8
vim.o.sidescrolloff = 8
vim.o.clipboard = 'unnamedplus' -- Use Linux system clipboard
vim.o.confirm = true
vim.o.backup = false  -- Disable backup for better performance
vim.o.updatetime = 250  -- Good balance for performance
vim.o.timeoutlen = 300  -- Faster key sequence completion
vim.o.redrawtime = 1500  -- More reasonable redraw time
vim.o.showmode = false
vim.o.fillchars = 'eob: '
vim.o.smartindent = true
vim.o.autoindent = true
vim.o.swapfile = false
vim.opt.cursorline = true
vim.opt.synmaxcol = 240  -- Limit syntax highlighting for better performance
vim.opt.ttyfast = true  -- Faster terminal connection
vim.opt.wrapscan = true  -- Better search performance
